[sftp.xi-x]
kind = "sftp"
host = "xiang233.top"
user = "xiang"
port = 22
key_file = "/home/xiang/.ssh/id_ed25519"

[sftp.xi-p]
kind = "sftp"
host = "xiang233.top"
user = "podman"
port = 22
key_file = "/home/xiang/.ssh/id_ed25519"

[sftp.xi-w]
kind = "sftp"
host = "xiang233.top"
user = "xiang"
port = 22022
key_file = "/home/xiang/.ssh/id_ed25519"
